import type { Destination, ExperienceCategory, Festival, PlanDay, Province, TravelTip } from "../types";

export const IMG = {
  hero: "https://images.unsplash.com/photo-1580424917967-a8867a6e676e?w=1920&h=1080&fit=crop&auto=format",
  valley: "https://images.unsplash.com/photo-1636513988093-126e51dee32d?w=900&h=600&fit=crop&auto=format",
  village: "https://images.unsplash.com/photo-1718179634911-8551f8b0cccf?w=900&h=600&fit=crop&auto=format",
  temple: "https://images.unsplash.com/photo-1507743617593-0a422c9bb7f5?w=900&h=600&fit=crop&auto=format",
  temple2: "https://images.unsplash.com/photo-1648298470994-7065f521375c?w=900&h=600&fit=crop&auto=format",
  pokhara: "https://images.unsplash.com/photo-1735533441842-33c5e47b22ae?w=900&h=600&fit=crop&auto=format",
  festival: "https://images.unsplash.com/photo-1622598661631-3a46559a4817?w=900&h=600&fit=crop&auto=format",
  culture: "https://images.unsplash.com/photo-1726326477267-f36f1740ad8e?w=900&h=600&fit=crop&auto=format",
  mountains: "https://images.unsplash.com/photo-1518002054494-3a6f94352e9d?w=1200&h=800&fit=crop&auto=format",
  women: "https://images.unsplash.com/photo-1763733593683-1b296c5fc039?w=900&h=600&fit=crop&auto=format",
};

export const experienceCategories: ExperienceCategory[] = [
  { icon: "🥾", label: "Hiking", color: "#1B5E3B" },
  { icon: "🛕", label: "Religious", color: "#8B1A1A" },
  { icon: "🏛️", label: "Historical", color: "#4A1573" },
  { icon: "🌿", label: "Nature", color: "#1B5E20" },
  { icon: "🦁", label: "Wildlife", color: "#E65100" },
  { icon: "🏔️", label: "Adventure", color: "#0D47A1" },
  { icon: "🍜", label: "Food", color: "#827717" },
  { icon: "🏨", label: "Stays", color: "#4E342E" },
];

export const destinations: Destination[] = [
  {
    id: 1,
    name: "Everest Base Camp",
    province: "Koshi",
    category: "Hiking",
    rating: 5.0,
    budget: "$800–1,500",
    season: "Mar–May, Sep–Nov",
    img: IMG.valley,
    desc: "Journey through Sherpa villages, glacial moraines, and monasteries to the foot of the world's highest peak.",
  },
  {
    id: 2,
    name: "Pashupatinath Temple",
    province: "Bagmati",
    category: "Religious",
    rating: 4.9,
    budget: "$5–20",
    season: "Year-round",
    img: IMG.temple,
    desc: "One of the most sacred Hindu shrines on earth — a UNESCO-listed golden pagoda on the Bagmati river.",
  },
  {
    id: 3,
    name: "Phewa Lake, Pokhara",
    province: "Gandaki",
    category: "Nature",
    rating: 4.8,
    budget: "$30–80",
    season: "Oct–May",
    img: IMG.pokhara,
    desc: "A serene lakeside destination with stunning mountain reflections and boat rides to Barahi Temple.",
  },
  {
    id: 4,
    name: "Boudhanath Stupa",
    province: "Bagmati",
    category: "Religious",
    rating: 4.8,
    budget: "$5–15",
    season: "Year-round",
    img: IMG.temple2,
    desc: "One of the largest spherical stupas in the world — a living center of Tibetan Buddhism.",
  },
];

export const provinces: Province[] = [
  {
    id: 1,
    name: "Koshi",
    nepali: "कोशी",
    capital: "Biratnagar",
    color: "#1B5E3B",
    light: "#E8F5EE",
    img: IMG.valley,
    highlights: ["Mt. Kanchenjunga", "Ilam Tea Gardens", "Makalu Base Camp"],
    description: "Eastern gateway to the Himalayas — lush tea estates, thundering rivers, and the mighty Kanchenjunga massif.",
    categories: ["🥾 Trekking", "🌿 Nature", "🦁 Wildlife", "🍵 Tea Culture"],
    topDest: ["Kanchenjunga Conservation Area", "Ilam Tea Estate", "Pathivara Temple", "Taplejung Valley"],
    bestSeason: "Oct–Nov, Mar–May",
    budget: "$25–60/day",
  },
  {
    id: 2,
    name: "Madhesh",
    nepali: "मधेश",
    capital: "Janakpur",
    color: "#8B1A1A",
    light: "#FDF0F0",
    img: IMG.temple2,
    highlights: ["Janaki Mandir", "Parsa Wildlife Reserve", "Simraungarh Ruins"],
    description: "The Terai heartland — birthplace of Goddess Sita and cradle of Maithili culture.",
    categories: ["🛕 Religious", "🏛️ Historical", "🦁 Wildlife", "🎭 Culture"],
    topDest: ["Janaki Mandir", "Parsa National Park", "Simraungarh Ruins", "Bihari Mandir"],
    bestSeason: "Oct–Feb",
    budget: "$15–40/day",
  },
  {
    id: 3,
    name: "Bagmati",
    nepali: "बागमती",
    capital: "Hetauda",
    color: "#4A1573",
    light: "#F3E8FF",
    img: IMG.temple,
    highlights: ["Kathmandu Valley", "Pashupatinath", "Chitwan National Park"],
    description: "Nepal's cultural capital — seven UNESCO sites, ancient palace squares, and the famous Chitwan National Park.",
    categories: ["🛕 Religious", "🏛️ Historical", "🌿 Nature", "🦁 Wildlife"],
    topDest: ["Pashupatinath Temple", "Boudhanath Stupa", "Chitwan National Park", "Bhaktapur Durbar Square"],
    bestSeason: "Oct–May",
    budget: "$30–80/day",
  },
  {
    id: 4,
    name: "Gandaki",
    nepali: "गण्डकी",
    capital: "Pokhara",
    color: "#0D47A1",
    light: "#E3F2FD",
    img: IMG.pokhara,
    highlights: ["Annapurna Circuit", "Phewa Lake", "Upper Mustang"],
    description: "Nepal's adventure capital — home to the Annapurna range, serene lakes, and Mustang's mystique.",
    categories: ["🥾 Trekking", "🏔️ Adventure", "🛕 Religious", "🌊 Lakes"],
    topDest: ["Annapurna Base Camp", "Phewa Lake Pokhara", "Muktinath Temple", "Upper Mustang Trek"],
    bestSeason: "Oct–Nov, Mar–May",
    budget: "$35–120/day",
  },
];

export const festivals: Festival[] = [
  {
    name: "Dashain",
    date: "Oct 2–12, 2025",
    province: "All Nepal",
    desc: "Nepal's biggest festival celebrating Durga's victory over evil with family, kites, and blessings.",
    img: IMG.culture,
  },
  {
    name: "Tihar / Diwali",
    date: "Oct 20–24, 2025",
    province: "All Nepal",
    desc: "Festival of lights where lamps illuminate homes and sisters bless brothers with Bhai Tika.",
    img: IMG.festival,
  },
  {
    name: "Indra Jatra",
    date: "Sep 4–12, 2025",
    province: "Kathmandu",
    desc: "Chariot processions and the living goddess Kumari celebrated through Kathmandu's old city.",
    img: IMG.temple2,
  },
  {
    name: "Buddha Jayanti",
    date: "May 12, 2026",
    province: "Lumbini & Kathmandu",
    desc: "The Buddha's birthday marked by candlelit processions and meditation at monasteries nationwide.",
    img: IMG.women,
  },
];

export const travelTips: TravelTip[] = [
  {
    icon: "🛂",
    title: "Visa on Arrival",
    desc: "Most nationalities can get a visa on arrival at the airport with 15-, 30-, or 90-day options.",
    color: "#0D47A1",
  },
  {
    icon: "💰",
    title: "Currency & ATMs",
    desc: "Nepalese Rupee (NPR). Carry cash when heading into trekking areas and remote provinces.",
    color: "#1B5E20",
  },
  {
    icon: "🌡️",
    title: "Altitude Sickness",
    desc: "Ascend slowly, hydrate, and know AMS symptoms when traveling above 3,000m.",
    color: "#8B1A1A",
  },
  {
    icon: "📱",
    title: "SIM & Connectivity",
    desc: "Buy Ncell or NTC SIM at the airport. Data is affordable, but signal is sparse in remote areas.",
    color: "#4E342E",
  },
  {
    icon: "🎒",
    title: "What to Pack",
    desc: "Layered clothing, sun protection, rain gear, trekking poles, and a power bank are essential.",
    color: "#4A1573",
  },
  {
    icon: "🙏",
    title: "Cultural Respect",
    desc: "Remove shoes at temples, walk clockwise around stupas, and use your right hand when giving.",
    color: "#E65100",
  },
];

export const planStyleOptions = [
  { value: "adventure", label: "🏔️ Adventure" },
  { value: "religious", label: "🛕 Religious" },
  { value: "family", label: "👨‍👩‍👧 Family" },
  { value: "couple", label: "💑 Couple" },
  { value: "solo", label: "🧍 Solo" },
  { value: "luxury", label: "✨ Luxury" },
  { value: "budget", label: "💚 Budget" },
];

export const planTemplates: Record<string, Omit<PlanDay, "day">[]> = {
  adventure: [
    {
      morning: "Trek to Annapurna Base Camp",
      afternoon: "Explore glacial moraines and mountain vistas",
      evening: "Lodge campfire with Himalayan views",
      hotel: "Annapurna Lodge",
      restaurant: "Sherpa Kitchen",
      cost: "$85–130",
      weather: "☀️ Clear, -5°C to 10°C",
    },
    {
      morning: "Sunrise at Machapuchare Viewpoint",
      afternoon: "Descend through rhododendron forests",
      evening: "Relax at Jhinu Danda hot springs",
      hotel: "Orchid Guest House",
      restaurant: "Local Dal Bhat Bhanchha",
      cost: "$55–90",
      weather: "🌤️ Partly cloudy, 5°C to 18°C",
    },
  ],
  religious: [
    {
      morning: "Pashupatinath Aarti ceremony",
      afternoon: "Boudhanath Stupa and monk visit",
      evening: "Butter lamps at Swayambhunath",
      hotel: "Heritage Hotel, Kathmandu",
      restaurant: "Krishnarpan",
      cost: "$85–150",
      weather: "☀️ Clear, 15°C to 25°C",
    },
    {
      morning: "Lumbini sacred garden walk",
      afternoon: "International monastery tour",
      evening: "Meditation session at a Tibetan monastery",
      hotel: "Buddha Garden Hotel",
      restaurant: "Garden of Dreams",
      cost: "$40–80",
      weather: "☀️ Sunny, 20°C to 30°C",
    },
  ],
  family: [
    {
      morning: "Chitwan jeep safari",
      afternoon: "Rapti river canoe ride",
      evening: "Tharu cultural dance show",
      hotel: "Tiger Tops Lodge",
      restaurant: "Wild Elephant Dining",
      cost: "$130–220",
      weather: "☀️ Sunny, 22°C to 32°C",
    },
    {
      morning: "Elephant Breeding Center visit",
      afternoon: "Boat tour to see crocodiles",
      evening: "Sunset riverside market walk",
      hotel: "Jungle Base Camp",
      restaurant: "Riverside Cafe",
      cost: "$100–180",
      weather: "🌤️ Partly sunny, 20°C to 30°C",
    },
  ],
  couple: [
    {
      morning: "Private sunrise boat ride on Phewa Lake",
      afternoon: "Lakeside spa session",
      evening: "Candlelit dinner with mountain view",
      hotel: "Temple Tree Resort",
      restaurant: "Hillside Restaurant",
      cost: "$120–220",
      weather: "☀️ Clear, 18°C to 28°C",
    },
    {
      morning: "Sarangkot viewpoint sunrise",
      afternoon: "Tandem paragliding over the valley",
      evening: "Sunset cruise with wine",
      hotel: "Temple Tree Resort",
      restaurant: "Boomerang Fine Dining",
      cost: "$150–280",
      weather: "☀️ Perfect visibility, 17°C to 27°C",
    },
  ],
  luxury: [
    {
      morning: "Helicopter tour over Everest Base Camp",
      afternoon: "Champagne picnic at altitude",
      evening: "Newari feast at a luxury hotel",
      hotel: "Dwarika's Heritage",
      restaurant: "Krishnarpan Private Dining",
      cost: "$900–1,600",
      weather: "☀️ Perfect visibility",
    },
    {
      morning: "Ayurvedic spa at Dwarika's",
      afternoon: "Private cultural guide tour",
      evening: "Rooftop sunset cocktails",
      hotel: "Dwarika's Heritage",
      restaurant: "Toran Restaurant",
      cost: "$400–700",
      weather: "☀️ Sunny, 18°C to 26°C",
    },
  ],
  budget: [
    {
      morning: "Swayambhunath early visit",
      afternoon: "Budget walk around Durbar Square",
      evening: "Street momo dinner",
      hotel: "Peace Guesthouse",
      restaurant: "OR2K Cafe",
      cost: "$15–28",
      weather: "☀️ Sunny, 16°C to 26°C",
    },
    {
      morning: "Pashupatinath temple visit",
      afternoon: "Boudhanath circumambulation",
      evening: "Local tea house experience",
      hotel: "Marco Polo Hostel",
      restaurant: "Bhojan Griha",
      cost: "$12–22",
      weather: "🌤️ Partly cloudy, 14°C to 24°C",
    },
  ],
};

export const mapFilters = [
  "Historical",
  "Religious",
  "Hotels",
  "Restaurants",
  "Hospitals",
  "ATM",
  "Bus Park",
  "Airport",
];
